provider: libvirt
machines:
    -   role: master
        name: journal-master
        box: generic/ubuntu2204
        memory: 9000  # in bytes
        cpu: 9
        ip: 10.100.100.40
    -   role: worker
        name: journal-worker1
        box: generic/ubuntu2204
        memory: 30000  # in bytes
        cpu: 30
        ip: 10.100.100.41
    -   role: worker
        name: journal-worker2
        box: generic/ubuntu2204
        memory: 20000  # in bytes
        cpu: 30
        ip: 10.100.100.42
